### ISSUE TITLE
provide cli interface - open ended

### ISSUE THREAD

**Issue by durangatan** [durangatan/midi-markov-python#1]
instead of simply running runner.py, it would be cool to offer a set of command line options for the tool. 
Some ideas:
- an option to name the midi file you output
- the ability to select a composer other than Bach
- the ability to select a different number of steps for the markov chain
- the ability to select a different phrase length

**Comment by Zenohm** [comment]
Files required to run the project are not present in this repository.

**Comment by durangatan** [comment]
Sorry about this! Looks like this relies on a midi module that doesn't exist anymore. Going to close this issue for now.
